#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : asciinema
Version  : 2.0.1
Release  : 1
URL      : https://github.com/asciinema/asciinema/archive/v2.0.1.tar.gz
Source0  : https://github.com/asciinema/asciinema/archive/v2.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: asciinema-bin = %{version}-%{release}
Requires: asciinema-license = %{version}-%{release}
Requires: asciinema-python = %{version}-%{release}
Requires: asciinema-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# asciinema
[![Build Status](https://travis-ci.org/asciinema/asciinema.svg?branch=master)](https://travis-ci.org/asciinema/asciinema)
[![PyPI](https://img.shields.io/pypi/v/asciinema.svg)](https://pypi.org/project/asciinema/)
[![license](http://img.shields.io/badge/license-GNU-blue.svg)](https://raw.githubusercontent.com/asciinema/asciinema/master/LICENSE)

%package bin
Summary: bin components for the asciinema package.
Group: Binaries
Requires: asciinema-license = %{version}-%{release}

%description bin
bin components for the asciinema package.


%package license
Summary: license components for the asciinema package.
Group: Default

%description license
license components for the asciinema package.


%package python
Summary: python components for the asciinema package.
Group: Default
Requires: asciinema-python3 = %{version}-%{release}

%description python
python components for the asciinema package.


%package python3
Summary: python3 components for the asciinema package.
Group: Default
Requires: python3-core

%description python3
python3 components for the asciinema package.


%prep
%setup -q -n asciinema-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539190926
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/asciinema
cp LICENSE %{buildroot}/usr/share/package-licenses/asciinema/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/asciinema

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/asciinema/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
